#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   IMPORTANT: this file's gradle-wrapper.jar counterpart is intentionally
#   NOT included in this delivery (see README.md / BUILD_REPORT.md): this
#   sandbox cannot fetch a compiled wrapper jar from a verified source.
#   Run `gradle wrapper --gradle-version 8.7` once (with a trusted local
#   Gradle install or from Android Studio) to generate it before building.
#
##############################################################################

APP_HOME=$(cd "$(dirname "$0")" >/dev/null && pwd)
APP_NAME="Gradle"
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

warn () { echo "$*"; } >&2
die () { echo; echo "$*"; echo; exit 1; } >&2

if [ -n "$JAVA_HOME" ]; then
    JAVACMD="$JAVA_HOME/bin/java"
else
    JAVACMD="java"
fi

CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

if [ ! -f "$CLASSPATH" ]; then
    die "ERROR: gradle-wrapper.jar no esta presente. Ejecuta 'gradle wrapper --gradle-version 8.7' con un Gradle local de confianza (o abre el proyecto en Android Studio) antes de compilar."
fi

exec "$JAVACMD" $DEFAULT_JVM_OPTS -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
