-- ============================================================
-- ClaseSmart - database/sample_data.sql
-- Generado automaticamente a partir del contenido semilla REAL
-- (app/src/main/java/com/educalab/clasesmart/data/seed/*.kt)
-- para garantizar que coincide exactamente con lo que la app
-- instalada siembra en el primer arranque.
-- ============================================================

INSERT INTO classroom (id, ownerId, currentLevel, activeThemeId, lastVisitedZone) VALUES
  ('main_classroom', 'local_user', 1, 'aula_base', 'aula_general');

INSERT INTO user_progress (id, totalXp, aulaLevel, sessionsCount, situationsResolved, projectsCompleted, lastSessionEpochMs) VALUES
  ('local_user', 0, 1, 0, 0, 0, 0);

INSERT INTO student_character (characterId, name, trait, spriteBaseId, defaultExpression) VALUES
  ('alex', 'Alex', 'Organizado', 'sprite_alex', 'CONCENTRADO'),
  ('mia', 'Mia', 'Creativa', 'sprite_mia', 'FELIZ'),
  ('leo', 'Leo', 'Curioso', 'sprite_leo', 'SORPRENDIDO'),
  ('sam', 'Sam', 'Tranquilo', 'sprite_sam', 'PENSATIVO'),
  ('dani', 'Dani', 'Energico', 'sprite_dani', 'FELIZ'),
  ('noa', 'Noa', 'Observadora', 'sprite_noa', 'CONCENTRADO'),
  ('teo', 'Teo', 'Constructor', 'sprite_teo', 'ORGULLOSO'),
  ('vera', 'Vera', 'Investigadora', 'sprite_vera', 'PENSATIVO'),
  ('bruno', 'Bruno', 'Comunicador', 'sprite_bruno', 'COLABORANDO'),
  ('cata', 'Cata', 'Cuidadosa', 'sprite_cata', 'PREOCUPADO');

INSERT INTO character_skill (characterId, skill, strength) VALUES
  ('alex', 'ORGANIZAR', 3),
  ('alex', 'CONSTRUIR', 1),
  ('mia', 'DIBUJAR', 3),
  ('mia', 'EXPLICAR', 1),
  ('leo', 'INVESTIGAR', 3),
  ('leo', 'OBSERVAR', 2),
  ('sam', 'OBSERVAR', 3),
  ('sam', 'ORGANIZAR', 1),
  ('dani', 'CONSTRUIR', 3),
  ('dani', 'EXPLICAR', 2),
  ('noa', 'OBSERVAR', 3),
  ('noa', 'INVESTIGAR', 2),
  ('teo', 'CONSTRUIR', 3),
  ('teo', 'ORGANIZAR', 2),
  ('vera', 'INVESTIGAR', 3),
  ('vera', 'DIBUJAR', 1),
  ('bruno', 'EXPLICAR', 3),
  ('bruno', 'ORGANIZAR', 1),
  ('cata', 'ORGANIZAR', 2),
  ('cata', 'OBSERVAR', 2);

INSERT INTO classroom_object (objectId, objectType, zoneX, zoneY, state, unlockLevel) VALUES
  ('obj_pizarra', 'PIZARRA', 0.5, 0.18, 'DISPONIBLE', 1),
  ('obj_reloj', 'RELOJ', 0.82, 0.14, 'DISPONIBLE', 1),
  ('obj_estante', 'ESTANTE', 0.12, 0.32, 'DISPONIBLE', 1),
  ('obj_pupitres', 'PUPITRES', 0.5, 0.6, 'BLOQUEADO', 2),
  ('obj_biblioteca', 'BIBLIOTECA', 0.85, 0.55, 'BLOQUEADO', 3),
  ('obj_mochila', 'MOCHILA', 0.2, 0.78, 'BLOQUEADO', 4),
  ('obj_puerta', 'PUERTA', 0.06, 0.6, 'BLOQUEADO', 5),
  ('obj_cartel_normas', 'CARTEL', 0.32, 0.1, 'DISPONIBLE', 1),
  ('obj_cartel_cumples', 'CARTEL', 0.68, 0.08, 'BLOQUEADO', 4),
  ('obj_planta_1', 'PLANTA', 0.05, 0.15, 'BLOQUEADO', 6),
  ('obj_planta_2', 'PLANTA', 0.95, 0.78, 'BLOQUEADO', 6),
  ('obj_papelera', 'PAPELERA', 0.9, 0.9, 'DISPONIBLE', 1),
  ('obj_ventana_1', 'CARTEL', 0.15, 0.05, 'DISPONIBLE', 1),
  ('obj_ventana_2', 'CARTEL', 0.85, 0.05, 'DISPONIBLE', 1),
  ('obj_mesa_1', 'PUPITRES', 0.3, 0.55, 'BLOQUEADO', 2),
  ('obj_mesa_2', 'PUPITRES', 0.7, 0.55, 'BLOQUEADO', 2),
  ('obj_mesa_3', 'PUPITRES', 0.5, 0.72, 'BLOQUEADO', 2),
  ('obj_estante_2', 'ESTANTE', 0.12, 0.45, 'DISPONIBLE', 1),
  ('obj_libro_1', 'BIBLIOTECA', 0.83, 0.45, 'BLOQUEADO', 3),
  ('obj_libro_2', 'BIBLIOTECA', 0.88, 0.62, 'BLOQUEADO', 3),
  ('obj_reloj_arena', 'RELOJ', 0.75, 0.2, 'DISPONIBLE', 1),
  ('obj_tiza_caja', 'PIZARRA', 0.42, 0.24, 'DISPONIBLE', 1),
  ('obj_borrador', 'PIZARRA', 0.58, 0.24, 'DISPONIBLE', 1),
  ('obj_silla_1', 'PUPITRES', 0.28, 0.63, 'BLOQUEADO', 2),
  ('obj_silla_2', 'PUPITRES', 0.72, 0.63, 'BLOQUEADO', 2),
  ('obj_alfombra', 'CARTEL', 0.5, 0.85, 'DISPONIBLE', 1),
  ('obj_perchero', 'MOCHILA', 0.08, 0.78, 'BLOQUEADO', 4),
  ('obj_calendario', 'RELOJ', 0.9, 0.28, 'DISPONIBLE', 1),
  ('obj_organizador', 'ESTANTE', 0.18, 0.38, 'DISPONIBLE', 1),
  ('obj_letrero_puerta', 'PUERTA', 0.1, 0.52, 'BLOQUEADO', 5);

INSERT INTO classroom_decoration (decorationId, name, category, unlockRequirement, requiredXp) VALUES
  ('dec_cartel_estrellas', 'Cartel de estrellas', 'CARTEL', 'Alcanza el nivel 2', 60),
  ('dec_cartel_planetas', 'Cartel de planetas', 'CARTEL', 'Alcanza el nivel 3', 150),
  ('dec_planta_cactus', 'Cactus de escritorio', 'PLANTA', 'Completa 3 misiones de materiales', 90),
  ('dec_planta_grande', 'Planta grande de rincon', 'PLANTA', 'Alcanza el nivel 6', 660),
  ('dec_pizarra_marco_madera', 'Marco de madera para la pizarra', 'PIZARRA_BORDE', 'Organiza 3 horarios sin problemas', 100),
  ('dec_pizarra_marco_color', 'Marco de colores para la pizarra', 'PIZARRA_BORDE', 'Organiza 5 horarios sin problemas', 200),
  ('dec_estante_cestas', 'Cestas organizadoras', 'ESTANTE_ADORNO', 'Prepara 5 misiones de materiales', 180),
  ('dec_estante_etiquetas', 'Etiquetas de colores', 'ESTANTE_ADORNO', 'Prepara 8 misiones de materiales', 260),
  ('dec_color_mesa_azul', 'Mesas color azul', 'COLOR_MUEBLE', 'Forma 2 equipos completos', 80),
  ('dec_color_mesa_verde', 'Mesas color verde', 'COLOR_MUEBLE', 'Forma 4 equipos completos', 160),
  ('dec_color_mesa_naranja', 'Mesas color naranja', 'COLOR_MUEBLE', 'Forma 6 equipos completos', 280),
  ('dec_cartel_cumples', 'Cartel de cumpleanos', 'CARTEL', 'Alcanza el nivel 4', 280),
  ('dec_alfombra_circulo', 'Alfombra de circulo', 'CARTEL', 'Resuelve 5 situaciones de convivencia', 120),
  ('dec_alfombra_mapa', 'Alfombra de mapa del mundo', 'CARTEL', 'Resuelve 10 situaciones de convivencia', 240),
  ('dec_movil_estrellas', 'Movil de estrellas colgante', 'CARTEL', 'Completa el primer proyecto del aula', 300),
  ('dec_guirnalda_banderines', 'Guirnalda de banderines', 'CARTEL', 'Completa 2 proyectos del aula', 500),
  ('dec_reloj_sol', 'Reloj de sol decorativo', 'CARTEL', 'Resuelve 5 retos de tiempo', 150),
  ('dec_perchero_colores', 'Perchero de colores', 'CARTEL', 'Alcanza el nivel 4', 280),
  ('dec_marco_fotos', 'Marco de fotos del equipo', 'CARTEL', 'Forma 8 equipos completos', 360),
  ('dec_luces_calidas', 'Luces calidas de rincon', 'CARTEL', 'Alcanza el nivel 6', 660);

INSERT INTO material (materialId, name, category, iconAssetId, isFragile, isShared) VALUES
  ('mat_lapiz', 'Lapiz', 'ESCRITURA', 'icon_lapiz', 0, 0),
  ('mat_goma', 'Goma de borrar', 'ESCRITURA', 'icon_goma', 0, 0),
  ('mat_regla', 'Regla', 'ESCRITURA', 'icon_regla', 0, 0),
  ('mat_tijeras', 'Tijeras de punta redonda', 'ARTE', 'icon_tijeras', 1, 0),
  ('mat_pegamento', 'Pegamento en barra', 'ARTE', 'icon_pegamento', 0, 0),
  ('mat_papel_color', 'Papel de colores', 'ARTE', 'icon_papel', 0, 0),
  ('mat_pinceles', 'Pinceles', 'ARTE', 'icon_pinceles', 0, 0),
  ('mat_pintura', 'Botes de pintura', 'ARTE', 'icon_pintura', 1, 0),
  ('mat_lupa', 'Lupa', 'CIENCIAS', 'icon_lupa', 1, 0),
  ('mat_recipiente', 'Recipiente transparente', 'CIENCIAS', 'icon_recipiente', 1, 0),
  ('mat_guantes', 'Guantes de observacion', 'CIENCIAS', 'icon_guantes', 0, 0),
  ('mat_cuaderno_campo', 'Cuaderno de campo', 'CIENCIAS', 'icon_cuaderno', 0, 0),
  ('mat_libro_cuentos', 'Libro de cuentos', 'LECTURA', 'icon_libro', 0, 1),
  ('mat_diccionario', 'Diccionario ilustrado', 'LECTURA', 'icon_diccionario', 0, 1),
  ('mat_marcapaginas', 'Marcapaginas', 'LECTURA', 'icon_marcapaginas', 0, 0),
  ('mat_carpeta', 'Carpeta clasificadora', 'ORGANIZACION', 'icon_carpeta', 0, 0),
  ('mat_etiquetas', 'Etiquetas adhesivas', 'ORGANIZACION', 'icon_etiquetas', 0, 0),
  ('mat_reloj_arena', 'Reloj de arena', 'ORGANIZACION', 'icon_reloj_arena', 0, 1),
  ('mat_caja_materiales', 'Caja de materiales compartidos', 'ORGANIZACION', 'icon_caja', 0, 1),
  ('mat_pizarra_mini', 'Pizarra individual', 'ESCRITURA', 'icon_pizarra_mini', 0, 0);

INSERT INTO material_location (materialId, zone, distanceUnits) VALUES
  ('mat_lapiz', 'ESTANTE', 1),
  ('mat_goma', 'ESTANTE', 2),
  ('mat_regla', 'ESTANTE', 3),
  ('mat_tijeras', 'ESTANTE', 4),
  ('mat_pegamento', 'ESTANTE', 1),
  ('mat_papel_color', 'ESTANTE', 2),
  ('mat_pinceles', 'ESTANTE', 3),
  ('mat_pintura', 'ESTANTE', 4),
  ('mat_lupa', 'ESTANTE', 1),
  ('mat_recipiente', 'ESTANTE', 2),
  ('mat_guantes', 'ESTANTE', 3),
  ('mat_cuaderno_campo', 'ESTANTE', 4),
  ('mat_libro_cuentos', 'ESTANTE', 1),
  ('mat_diccionario', 'ESTANTE', 2),
  ('mat_marcapaginas', 'ESTANTE', 3),
  ('mat_carpeta', 'ESTANTE', 4),
  ('mat_etiquetas', 'ESTANTE', 1),
  ('mat_reloj_arena', 'ESTANTE', 2),
  ('mat_caja_materiales', 'ESTANTE', 3),
  ('mat_pizarra_mini', 'ESTANTE', 4);

INSERT INTO badge (badgeId, name, description, iconAssetId, skillArea) VALUES
  ('gran_organizador', 'Gran Organizador', 'Organizaste el horario del aula sin dejar nada suelto.', 'icon_badge_organizador', 'ORGANIZACION'),
  ('maestro_del_tiempo', 'Maestro del Tiempo', 'Sabes calcular cuanto dura cada cosa y que cabe en la jornada.', 'icon_badge_tiempo', 'TIEMPO'),
  ('equipo_imparable', 'Equipo Imparable', 'Formaste equipos donde nadie se quedaba sin apoyo.', 'icon_badge_equipo', 'EQUIPO'),
  ('guardian_de_materiales', 'Guardian de Materiales', 'Preparaste los materiales exactos para cada actividad.', 'icon_badge_materiales', 'MATERIALES'),
  ('solucionador_de_problemas', 'Solucionador de Problemas', 'Encontraste buenas soluciones en situaciones dificiles.', 'icon_badge_solucionador', 'CONVIVENCIA'),
  ('gran_comunicador', 'Gran Comunicador', 'Ayudaste a que todos se entendieran mejor.', 'icon_badge_comunicador', 'COMUNICACION'),
  ('constructor_de_ideas', 'Constructor de Ideas', 'Llenaste la pizarra de ideas conectadas.', 'icon_badge_ideas', 'PROYECTO'),
  ('ayudante_del_aula', 'Ayudante del Aula', 'Resolviste muchas situaciones ayudando a companeros.', 'icon_badge_ayudante', 'CONVIVENCIA'),
  ('planificador_creativo', 'Planificador Creativo', 'Tus horarios funcionan una y otra vez.', 'icon_badge_planificador', 'ORGANIZACION'),
  ('experto_en_colaboracion', 'Experto en Colaboracion', 'Formaste muchos equipos que se complementan.', 'icon_badge_colaboracion', 'EQUIPO'),
  ('cuidador_del_espacio', 'Cuidador del Espacio', 'Cuidaste y decoraste el aula con esfuerzo real.', 'icon_badge_cuidador', 'ORGANIZACION'),
  ('lider_de_proyecto', 'Lider de Proyecto', 'Llevaste un gran proyecto del aula hasta el final.', 'icon_badge_lider', 'PROYECTO');

INSERT INTO class_activity (activityId, title, subject, durationMinutes, minAgeBand, requiredMaterialIds) VALUES
  ('act_lectura', 'Lectura compartida', 'LECTURA', 20, '8-9', 'mat_libro_cuentos,mat_marcapaginas'),
  ('act_ciencias', 'Experimento de observacion', 'CIENCIAS', 40, '8-9', 'mat_lupa,mat_recipiente,mat_cuaderno_campo'),
  ('act_arte', 'Mural colaborativo', 'ARTE', 35, '8-9', 'mat_papel_color,mat_pinceles,mat_pintura'),
  ('act_matematicas', 'Reto de calculo en equipo', 'MATEMATICAS', 30, '10-12', 'mat_pizarra_mini,mat_lapiz'),
  ('act_trabajo_grupal', 'Investigacion en grupos', 'TRABAJO_GRUPAL', 35, '10-12', 'mat_diccionario,mat_carpeta'),
  ('act_limpieza', 'Orden del aula', 'LIMPIEZA', 10, '8-9', ''),
  ('act_exposicion', 'Presentacion de proyectos', 'EXPOSICION', 25, '10-12', 'mat_pizarra_mini'),
  ('act_recreo', 'Recreo', 'RECREO', 20, '8-9', '');

INSERT INTO activity_step (activityId, orderIndex, instruction) VALUES
  ('act_ciencias', 0, 'Observa el objeto con la lupa.'),
  ('act_ciencias', 1, 'Anota lo que ves en el cuaderno de campo.'),
  ('act_ciencias', 2, 'Comparte tu observacion con el grupo.'),
  ('act_arte', 0, 'Elige los colores del mural.'),
  ('act_arte', 1, 'Reparte las zonas entre el equipo.'),
  ('act_arte', 2, 'Pinta y deja secar antes de tocar.');

INSERT INTO time_block (timeBlockId, dayLabel, startMinute, endMinute, isRecess) VALUES
  ('block_1', 'Hoy', 0, 40, 0),
  ('block_2', 'Hoy', 40, 80, 0),
  ('block_3', 'Hoy', 80, 100, 1),
  ('block_4', 'Hoy', 100, 140, 0),
  ('block_5', 'Hoy', 140, 175, 0),
  ('block_6', 'Hoy', 175, 210, 0),
  ('block_7', 'Hoy', 210, 235, 0),
  ('block_8', 'Hoy', 235, 255, 0);

INSERT INTO classroom_situation (situationId, title, sceneDescription, category, minAgeBand, involvedCharacterIds) VALUES
  ('sit_conv_1', 'El mismo material', 'Alex y Mia quieren usar la unica lupa al mismo tiempo.', 'CONVIVENCIA', '8-9', 'alex,mia'),
  ('sit_conv_2', 'El material olvidado', 'Leo llego sin su carpeta de trabajo grupal.', 'CONVIVENCIA', '8-9', 'leo,sam'),
  ('sit_conv_3', 'El companero interrumpe', 'Dani sigue hablando mientras Noa intenta explicar su idea.', 'CONVIVENCIA', '10-12', 'dani,noa'),
  ('sit_conv_4', 'Alguien se quedo fuera', 'El grupo eligio equipo y Cata se quedo sin sitio.', 'CONVIVENCIA', '8-9', 'cata,teo'),
  ('sit_conv_5', 'Un error sin querer', 'Bruno tiro sin querer el mural que preparaba Vera.', 'CONVIVENCIA', '10-12', 'bruno,vera'),
  ('sit_org_1', 'El aula quedo desordenada', 'Despues de arte, los pinceles quedaron por todas las mesas.', 'ORGANIZACION', '8-9', 'mia,teo'),
  ('sit_org_2', 'El grupo no sabe por donde empezar', 'El equipo de ciencias mira el material sin decidir el primer paso.', 'ORGANIZACION', '10-12', 'leo,vera'),
  ('sit_org_3', 'Demasiadas cosas sobre la mesa', 'La mesa de Sam tiene materiales de tres actividades distintas mezclados.', 'ORGANIZACION', '8-9', 'sam'),
  ('sit_org_4', 'Nadie recogio la pizarra', 'La pizarra sigue llena de la clase anterior y hace falta para hoy.', 'ORGANIZACION', '8-9', 'alex,dani'),
  ('sit_org_5', 'El plan cambio a mitad de actividad', 'A mitad del mural, el equipo decide cambiar el diseno sin avisar a todos.', 'ORGANIZACION', '10-12', 'noa,cata,bruno'),
  ('sit_tiempo_1', 'Poco tiempo antes del recreo', 'Quedan 15 minutos y todavia falta terminar el mural.', 'TIEMPO', '8-9', 'mia,teo'),
  ('sit_tiempo_2', 'La exposicion se alarga', 'Cada equipo esta usando mas tiempo del previsto para presentar.', 'TIEMPO', '10-12', 'bruno,vera'),
  ('sit_tiempo_3', 'El experimento va mas lento de lo pensado', 'El equipo de ciencias necesita mas minutos de los que quedan.', 'TIEMPO', '10-12', 'leo,noa'),
  ('sit_tiempo_4', 'Llego tarde el material', 'El material para matematicas llego 10 minutos tarde a la mesa.', 'TIEMPO', '8-9', 'alex,sam'),
  ('sit_tiempo_5', 'Demasiadas tareas para hoy', 'El horario de hoy tiene mas actividades de las que caben.', 'TIEMPO', '10-12', 'cata,dani'),
  ('sit_mat_1', 'Se perdio un material', 'La lupa que se uso ayer no aparece en el estante.', 'MATERIALES', '8-9', 'leo'),
  ('sit_mat_2', 'Falta un material clave', 'Para el experimento hace falta el recipiente y no esta preparado.', 'MATERIALES', '8-9', 'vera,noa'),
  ('sit_mat_3', 'Material fragil en manos poco cuidadosas', 'Dani lleva los botes de pintura corriendo hacia la mesa.', 'MATERIALES', '8-9', 'dani'),
  ('sit_mat_4', 'Todos quieren el mismo color', 'Varios companeros quieren el mismo papel de color para el mural.', 'MATERIALES', '8-9', 'mia,cata,bruno'),
  ('sit_mat_5', 'Material compartido sin devolver', 'El diccionario compartido sigue en la mesa de ayer.', 'MATERIALES', '10-12', 'sam,teo'),
  ('sit_equipo_1', 'Un equipo no se organiza', 'El grupo de matematicas lleva 5 minutos sin decidir quien hace que.', 'EQUIPO', '10-12', 'alex,dani,cata'),
  ('sit_equipo_2', 'Todos quieren dibujar', 'En el equipo de arte, nadie quiere encargarse de explicar el resultado.', 'EQUIPO', '8-9', 'mia,bruno'),
  ('sit_equipo_3', 'Falta alguien que investigue', 'El equipo de ciencias no tiene a nadie comodo buscando informacion.', 'EQUIPO', '10-12', 'teo,sam'),
  ('sit_equipo_4', 'Un compañero se queda callado', 'Vera no esta participando en las decisiones del equipo.', 'EQUIPO', '10-12', 'vera,leo'),
  ('sit_equipo_5', 'Dos lideres a la vez', 'Alex y Noa quieren decidir el mismo paso del proyecto por su cuenta.', 'EQUIPO', '10-12', 'alex,noa'),
  ('sit_plan_1', 'El proyecto no tiene primer paso', 'El equipo de la Feria de Ideas no sabe por donde empezar a planificar.', 'PLANIFICACION', '10-12', 'bruno,vera,teo'),
  ('sit_plan_2', 'Cambio de ultimo momento', 'El espacio reservado para la exposicion ya no esta disponible.', 'PLANIFICACION', '10-12', 'cata,alex'),
  ('sit_plan_3', 'Demasiadas ideas a la vez', 'La pizarra de ideas se lleno de propuestas sin ningun orden.', 'PLANIFICACION', '10-12', 'mia,leo,dani'),
  ('sit_plan_4', 'Nadie anoto el plan', 'El equipo decidio los pasos de palabra, pero nadie los escribio.', 'PLANIFICACION', '10-12', 'sam,noa'),
  ('sit_plan_5', 'El plan no dejo tiempo para imprevistos', 'El proyecto va bien, pero un imprevisto puede dejarlos sin margen.', 'PLANIFICACION', '10-12', 'teo,cata,bruno');

INSERT INTO situation_option (optionId, situationId, actionLabel, qualityLevel) VALUES
  ('opt_conv1_a', 'sit_conv_1', 'Repartir el tiempo de uso de la lupa', 2),
  ('opt_conv1_b', 'sit_conv_1', 'Decirle a Mia que espere, sin mas', 1),
  ('opt_conv1_c', 'sit_conv_1', 'Quedarse Alex con la lupa todo el rato', 0),
  ('opt_conv2_a', 'sit_conv_2', 'Compartir la carpeta de Sam por turnos', 2),
  ('opt_conv2_b', 'sit_conv_2', 'Dejar que Leo trabaje sin carpeta como pueda', 1),
  ('opt_conv2_c', 'sit_conv_2', 'Decirle a Leo que deberia haberse acordado', 0),
  ('opt_conv3_a', 'sit_conv_3', 'Proponer turnos para hablar', 2),
  ('opt_conv3_b', 'sit_conv_3', 'Pedirle a Dani que baje la voz', 1),
  ('opt_conv3_c', 'sit_conv_3', 'Dejar que Noa no termine de explicar', 0),
  ('opt_conv4_a', 'sit_conv_4', 'Abrir un puesto mas en el equipo para Cata', 2),
  ('opt_conv4_b', 'sit_conv_4', 'Decirle a Cata que se una a otro grupo cualquiera', 1),
  ('opt_conv4_c', 'sit_conv_4', 'No hacer nada y seguir sin ella', 0),
  ('opt_conv5_a', 'sit_conv_5', 'Ayudar entre todos a rehacer la parte danada', 2),
  ('opt_conv5_b', 'sit_conv_5', 'Pedir disculpas y seguir sin arreglarlo', 1),
  ('opt_conv5_c', 'sit_conv_5', 'Culpar a Bruno delante del grupo', 0),
  ('opt_org1_a', 'sit_org_1', 'Organizar entre todos donde va cada pincel', 2),
  ('opt_org1_b', 'sit_org_1', 'Dejarlos amontonados en el estante', 1),
  ('opt_org1_c', 'sit_org_1', 'Dejarlos donde estan y empezar otra actividad', 0),
  ('opt_org2_a', 'sit_org_2', 'Escribir juntos los pasos antes de tocar el material', 2),
  ('opt_org2_b', 'sit_org_2', 'Empezar cada uno por su cuenta', 1),
  ('opt_org2_c', 'sit_org_2', 'Esperar a que alguien mas decida por ellos', 0),
  ('opt_org3_a', 'sit_org_3', 'Separar los materiales por actividad antes de seguir', 2),
  ('opt_org3_b', 'sit_org_3', 'Apartar solo lo que se usa ahora mismo', 1),
  ('opt_org3_c', 'sit_org_3', 'Seguir trabajando con todo mezclado', 0),
  ('opt_org4_a', 'sit_org_4', 'Borrarla entre dos antes de empezar', 2),
  ('opt_org4_b', 'sit_org_4', 'Esperar a que la profesora la borre', 1),
  ('opt_org4_c', 'sit_org_4', 'Escribir encima sin borrar', 0),
  ('opt_org5_a', 'sit_org_5', 'Reunir al equipo un minuto para contar el cambio', 2),
  ('opt_org5_b', 'sit_org_5', 'Avisar solo a quien esta al lado', 1),
  ('opt_org5_c', 'sit_org_5', 'Seguir cada uno con el plan que tenia antes', 0),
  ('opt_tiempo1_a', 'sit_tiempo_1', 'Repartir lo que falta entre todo el equipo', 2),
  ('opt_tiempo1_b', 'sit_tiempo_1', 'Seguir trabajando igual de rapido sin cambiar nada', 1),
  ('opt_tiempo1_c', 'sit_tiempo_1', 'Dejarlo a medias sin avisar a nadie', 0),
  ('opt_tiempo2_a', 'sit_tiempo_2', 'Acordar un tiempo maximo igual para cada equipo', 2),
  ('opt_tiempo2_b', 'sit_tiempo_2', 'Pedir a los ultimos que se den prisa', 1),
  ('opt_tiempo2_c', 'sit_tiempo_2', 'Dejar que unos equipos no lleguen a presentar', 0),
  ('opt_tiempo3_a', 'sit_tiempo_3', 'Simplificar el ultimo paso para llegar a tiempo', 2),
  ('opt_tiempo3_b', 'sit_tiempo_3', 'Seguir igual y terminar tarde', 1),
  ('opt_tiempo3_c', 'sit_tiempo_3', 'Dejar el experimento sin anotar resultados', 0),
  ('opt_tiempo4_a', 'sit_tiempo_4', 'Empezar con otra parte de la actividad mientras llega', 2),
  ('opt_tiempo4_b', 'sit_tiempo_4', 'Esperar sin hacer nada hasta que llegue', 1),
  ('opt_tiempo4_c', 'sit_tiempo_4', 'Cancelar la actividad por el retraso', 0),
  ('opt_tiempo5_a', 'sit_tiempo_5', 'Elegir juntos que actividad mover a manana', 2),
  ('opt_tiempo5_b', 'sit_tiempo_5', 'Intentar hacer todo mas rapido y peor', 1),
  ('opt_tiempo5_c', 'sit_tiempo_5', 'Dejar que el dia se desordene sin decidir nada', 0),
  ('opt_mat1_a', 'sit_mat_1', 'Buscar juntos en las zonas donde pudo quedar', 2),
  ('opt_mat1_b', 'sit_mat_1', 'Usar otra lupa distinta sin buscar la primera', 1),
  ('opt_mat1_c', 'sit_mat_1', 'Empezar la actividad sin lupa', 0),
  ('opt_mat2_a', 'sit_mat_2', 'Prepararlo antes de empezar la actividad', 2),
  ('opt_mat2_b', 'sit_mat_2', 'Improvisar con otro recipiente parecido', 1),
  ('opt_mat2_c', 'sit_mat_2', 'Empezar sin el y ver que pasa', 0),
  ('opt_mat3_a', 'sit_mat_3', 'Pedirle a Dani que camine y lleve los botes con cuidado', 2),
  ('opt_mat3_b', 'sit_mat_3', 'Dejarlo seguir igual, total no paso nada todavia', 1),
  ('opt_mat3_c', 'sit_mat_3', 'No decir nada aunque se pueda romper algo', 0),
  ('opt_mat4_a', 'sit_mat_4', 'Repartir turnos para usar ese color', 2),
  ('opt_mat4_b', 'sit_mat_4', 'Quedarselo quien llego primero sin mas', 1),
  ('opt_mat4_c', 'sit_mat_4', 'Discutir sin llegar a ningun acuerdo', 0),
  ('opt_mat5_a', 'sit_mat_5', 'Devolverlo al estante antes de empezar otra cosa', 2),
  ('opt_mat5_b', 'sit_mat_5', 'Usarlo de todas formas sin devolverlo despues', 1),
  ('opt_mat5_c', 'sit_mat_5', 'Dejarlo donde esta para que otro lo mueva', 0),
  ('opt_equipo1_a', 'sit_equipo_1', 'Repartir tareas segun lo que cada uno hace mejor', 2),
  ('opt_equipo1_b', 'sit_equipo_1', 'Repartir tareas al azar para empezar ya', 1),
  ('opt_equipo1_c', 'sit_equipo_1', 'Seguir sin repartir nada', 0),
  ('opt_equipo2_a', 'sit_equipo_2', 'Buscar quien se sienta comodo explicando, aunque no sea quien mas dibuja', 2),
  ('opt_equipo2_b', 'sit_equipo_2', 'Elegir a quien este mas cerca de la pizarra', 1),
  ('opt_equipo2_c', 'sit_equipo_2', 'No presentar el resultado del equipo', 0),
  ('opt_equipo3_a', 'sit_equipo_3', 'Sumar a alguien de otro equipo que investiga bien', 2),
  ('opt_equipo3_b', 'sit_equipo_3', 'Repartir la busqueda entre todos igual, sepan o no', 1),
  ('opt_equipo3_c', 'sit_equipo_3', 'Dejar la investigacion sin hacer', 0),
  ('opt_equipo4_a', 'sit_equipo_4', 'Preguntarle a Vera directamente que opina', 2),
  ('opt_equipo4_b', 'sit_equipo_4', 'Seguir decidiendo sin contar con ella', 1),
  ('opt_equipo4_c', 'sit_equipo_4', 'Decirle que no participa nunca delante de todos', 0),
  ('opt_equipo5_a', 'sit_equipo_5', 'Repartir ese paso en dos partes complementarias', 2),
  ('opt_equipo5_b', 'sit_equipo_5', 'Decidir con una moneda quien manda ese paso', 1),
  ('opt_equipo5_c', 'sit_equipo_5', 'Discutir sin llegar a ponerse de acuerdo', 0),
  ('opt_plan1_a', 'sit_plan_1', 'Escribir juntos los primeros tres pasos', 2),
  ('opt_plan1_b', 'sit_plan_1', 'Empezar por lo primero que se les ocurra', 1),
  ('opt_plan1_c', 'sit_plan_1', 'Seguir sin decidir nada mas tiempo', 0),
  ('opt_plan2_a', 'sit_plan_2', 'Buscar juntos un espacio alternativo ahora mismo', 2),
  ('opt_plan2_b', 'sit_plan_2', 'Esperar a ver si el espacio se libera solo', 1),
  ('opt_plan2_c', 'sit_plan_2', 'Cancelar la exposicion sin buscar alternativa', 0),
  ('opt_plan3_a', 'sit_plan_3', 'Agrupar las ideas parecidas antes de seguir', 2),
  ('opt_plan3_b', 'sit_plan_3', 'Elegir la primera idea que aparecio', 1),
  ('opt_plan3_c', 'sit_plan_3', 'Dejar todas las ideas sueltas sin ordenar', 0),
  ('opt_plan4_a', 'sit_plan_4', 'Escribir el plan en la pizarra antes de seguir', 2),
  ('opt_plan4_b', 'sit_plan_4', 'Confiar en que todos lo recuerden igual', 1),
  ('opt_plan4_c', 'sit_plan_4', 'Seguir sin anotar nada', 0),
  ('opt_plan5_a', 'sit_plan_5', 'Dejar un bloque de tiempo libre por si surge algo', 2),
  ('opt_plan5_b', 'sit_plan_5', 'Seguir con el plan tal cual, sin margen', 1),
  ('opt_plan5_c', 'sit_plan_5', 'No pensar en los imprevistos hasta que pasen', 0);

INSERT INTO situation_outcome (outcomeId, optionId, consequenceText, xpAwarded) VALUES
  ('out_conv1_a', 'opt_conv1_a', 'Los dos pudieron observar y nadie se quedo esperando de mas.', 15),
  ('out_conv1_b', 'opt_conv1_b', 'Mia espero, pero se perdio parte de la actividad mientras tanto.', 8),
  ('out_conv1_c', 'opt_conv1_c', 'Mia no pudo observar nada durante toda la actividad.', 2),
  ('out_conv2_a', 'opt_conv2_a', 'Ambos pudieron trabajar y Leo aprendio a pedir ayuda a tiempo.', 15),
  ('out_conv2_b', 'opt_conv2_b', 'Leo pudo seguir, pero le costo mas de lo necesario.', 8),
  ('out_conv2_c', 'opt_conv2_c', 'Leo se quedo sin poder participar en la actividad.', 2),
  ('out_conv3_a', 'opt_conv3_a', 'Todos pudieron hablar y Noa termino de explicar su idea.', 15),
  ('out_conv3_b', 'opt_conv3_b', 'Dani bajo la voz, pero Noa tuvo que repetir parte de lo dicho.', 8),
  ('out_conv3_c', 'opt_conv3_c', 'Noa no pudo compartir su idea con el grupo.', 2),
  ('out_conv4_a', 'opt_conv4_a', 'Cata se sumo al equipo y aporto una habilidad que faltaba.', 15),
  ('out_conv4_b', 'opt_conv4_b', 'Cata encontro sitio, pero no en el equipo donde queria estar.', 8),
  ('out_conv4_c', 'opt_conv4_c', 'Cata se quedo sin equipo para la actividad.', 2),
  ('out_conv5_a', 'opt_conv5_a', 'El mural quedo reparado y el equipo aprendio a resolverlo juntos.', 15),
  ('out_conv5_b', 'opt_conv5_b', 'Vera acepto las disculpas, pero el mural quedo sin terminar.', 8),
  ('out_conv5_c', 'opt_conv5_c', 'Bruno se sintio mal y el mural tampoco se arreglo.', 2),
  ('out_org1_a', 'opt_org1_a', 'El estante quedo listo y la siguiente clase encontrara todo rapido.', 15),
  ('out_org1_b', 'opt_org1_b', 'Los pinceles estan guardados, pero sera dificil encontrarlos despues.', 8),
  ('out_org1_c', 'opt_org1_c', 'El desorden sigue igual para la siguiente actividad.', 2),
  ('out_org2_a', 'opt_org2_a', 'El equipo empezo con un plan claro y avanzo mas rapido.', 15),
  ('out_org2_b', 'opt_org2_b', 'Cada quien avanzo por su lado y luego costo juntar el trabajo.', 8),
  ('out_org2_c', 'opt_org2_c', 'El grupo perdio varios minutos sin empezar nada.', 2),
  ('out_org3_a', 'opt_org3_a', 'Sam pudo trabajar con espacio y sin confundir materiales.', 15),
  ('out_org3_b', 'opt_org3_b', 'Sam pudo seguir, aunque la mesa siguio algo apretada.', 8),
  ('out_org3_c', 'opt_org3_c', 'Sam mezclo materiales de actividades distintas por error.', 2),
  ('out_org4_a', 'opt_org4_a', 'La pizarra quedo lista justo a tiempo para la clase.', 15),
  ('out_org4_b', 'opt_org4_b', 'La clase empezo un poco tarde esperando a que la borraran.', 8),
  ('out_org4_c', 'opt_org4_c', 'La pizarra quedo dificil de leer, mezclada con lo anterior.', 2),
  ('out_org5_a', 'opt_org5_a', 'Todo el equipo siguio el nuevo plan a la vez, sin confusiones.', 15),
  ('out_org5_b', 'opt_org5_b', 'Una parte del equipo se entero tarde del cambio.', 8),
  ('out_org5_c', 'opt_org5_c', 'El mural quedo con dos diseños distintos mezclados.', 2),
  ('out_tiempo1_a', 'opt_tiempo1_a', 'El mural quedo terminado justo antes del recreo.', 15),
  ('out_tiempo1_b', 'opt_tiempo1_b', 'El mural quedo casi listo, con una parte a medias.', 8),
  ('out_tiempo1_c', 'opt_tiempo1_c', 'El mural quedo sin terminar y nadie sabia que faltaba.', 2),
  ('out_tiempo2_a', 'opt_tiempo2_a', 'Todos los equipos pudieron presentar en el tiempo disponible.', 15),
  ('out_tiempo2_b', 'opt_tiempo2_b', 'Se presento todo, pero los ultimos equipos fueron con prisa.', 8),
  ('out_tiempo2_c', 'opt_tiempo2_c', 'Algunos equipos se quedaron sin presentar su trabajo.', 2),
  ('out_tiempo3_a', 'opt_tiempo3_a', 'El experimento se cerro a tiempo con una conclusion clara.', 15),
  ('out_tiempo3_b', 'opt_tiempo3_b', 'El experimento termino, pero se corto el siguiente bloque.', 8),
  ('out_tiempo3_c', 'opt_tiempo3_c', 'No quedo registro de lo que se observo.', 2),
  ('out_tiempo4_a', 'opt_tiempo4_a', 'El equipo aprovecho el tiempo y no se quedo parado.', 15),
  ('out_tiempo4_b', 'opt_tiempo4_b', 'El equipo perdio minutos valiosos esperando sin avanzar.', 8),
  ('out_tiempo4_c', 'opt_tiempo4_c', 'La actividad no se llego a hacer ese dia.', 2),
  ('out_tiempo5_a', 'opt_tiempo5_a', 'El dia quedo mejor repartido y con tiempo real para cada cosa.', 15),
  ('out_tiempo5_b', 'opt_tiempo5_b', 'Todo se hizo, pero con mucha prisa y algo de estres.', 8),
  ('out_tiempo5_c', 'opt_tiempo5_c', 'El dia quedo desordenado y varias cosas quedaron a medias.', 2),
  ('out_mat1_a', 'opt_mat1_a', 'La lupa aparecio y el equipo entendio donde guardarla despues.', 15),
  ('out_mat1_b', 'opt_mat1_b', 'La actividad siguio, pero la lupa original sigue perdida.', 8),
  ('out_mat1_c', 'opt_mat1_c', 'El equipo no pudo observar los detalles pequenos.', 2),
  ('out_mat2_a', 'opt_mat2_a', 'El experimento empezo sin interrupciones.', 15),
  ('out_mat2_b', 'opt_mat2_b', 'El experimento funciono, aunque no de forma exacta.', 8),
  ('out_mat2_c', 'opt_mat2_c', 'El experimento no se pudo completar bien.', 2),
  ('out_mat3_a', 'opt_mat3_a', 'Los botes de pintura llegaron enteros a la mesa.', 15),
  ('out_mat3_b', 'opt_mat3_b', 'Esta vez no paso nada, pero el riesgo seguia ahi.', 8),
  ('out_mat3_c', 'opt_mat3_c', 'Uno de los botes se cayo y hubo que limpiar.', 2),
  ('out_mat4_a', 'opt_mat4_a', 'Todos pudieron usar el color que necesitaban en algun momento.', 15),
  ('out_mat4_b', 'opt_mat4_b', 'Solo uno pudo usarlo y los demas cambiaron de color molestos.', 8),
  ('out_mat4_c', 'opt_mat4_c', 'Se perdio tiempo discutiendo en vez de trabajar.', 2),
  ('out_mat5_a', 'opt_mat5_a', 'El diccionario quedo listo para quien lo necesite despues.', 15),
  ('out_mat5_b', 'opt_mat5_b', 'El diccionario se uso, pero nadie sabra donde buscarlo luego.', 8),
  ('out_mat5_c', 'opt_mat5_c', 'El diccionario sigue perdido para el resto de la clase.', 2),
  ('out_equipo1_a', 'opt_equipo1_a', 'Cada quien trabajo en lo que se le daba mejor y avanzaron rapido.', 15),
  ('out_equipo1_b', 'opt_equipo1_b', 'El equipo avanzo, aunque algunas tareas costaron mas de lo normal.', 8),
  ('out_equipo1_c', 'opt_equipo1_c', 'El equipo siguio parado sin avanzar en la actividad.', 2),
  ('out_equipo2_a', 'opt_equipo2_a', 'La presentacion salio clara y todos se sintieron utiles.', 15),
  ('out_equipo2_b', 'opt_equipo2_b', 'La presentacion salio adelante, aunque con algo de improvisacion.', 8),
  ('out_equipo2_c', 'opt_equipo2_c', 'El trabajo del equipo no se llego a mostrar.', 2),
  ('out_equipo3_a', 'opt_equipo3_a', 'El equipo consiguio la informacion que necesitaba a tiempo.', 15),
  ('out_equipo3_b', 'opt_equipo3_b', 'Consiguieron algo de informacion, aunque les costo bastante.', 8),
  ('out_equipo3_c', 'opt_equipo3_c', 'El proyecto quedo sin la informacion que necesitaba.', 2),
  ('out_equipo4_a', 'opt_equipo4_a', 'Vera compartio una idea que mejoro el plan del equipo.', 15),
  ('out_equipo4_b', 'opt_equipo4_b', 'El equipo siguio adelante sin la idea de Vera.', 8),
  ('out_equipo4_c', 'opt_equipo4_c', 'Vera se sintio peor y participo todavia menos.', 2),
  ('out_equipo5_a', 'opt_equipo5_a', 'Alex y Noa combinaron sus ideas en un paso mejor.', 15),
  ('out_equipo5_b', 'opt_equipo5_b', 'Se resolvio rapido, aunque uno de los dos quedo algo descontento.', 8),
  ('out_equipo5_c', 'opt_equipo5_c', 'El equipo perdio tiempo sin avanzar ese paso.', 2),
  ('out_plan1_a', 'opt_plan1_a', 'El proyecto arranco con una base clara para seguir.', 15),
  ('out_plan1_b', 'opt_plan1_b', 'El proyecto arranco, aunque tuvieron que corregir el rumbo despues.', 8),
  ('out_plan1_c', 'opt_plan1_c', 'El proyecto sigue sin un primer paso claro.', 2),
  ('out_plan2_a', 'opt_plan2_a', 'Encontraron un espacio nuevo y la exposicion siguio en pie.', 15),
  ('out_plan2_b', 'opt_plan2_b', 'El espacio aparecio justo a tiempo, con poco margen.', 8),
  ('out_plan2_c', 'opt_plan2_c', 'La exposicion se quedo sin lugar donde hacerse.', 2),
  ('out_plan3_a', 'opt_plan3_a', 'La pizarra quedo ordenada y facil de seguir para todos.', 15),
  ('out_plan3_b', 'opt_plan3_b', 'Avanzaron con una idea, aunque quiza no era la mas completa.', 8),
  ('out_plan3_c', 'opt_plan3_c', 'La pizarra siguio siendo dificil de entender para el equipo.', 2),
  ('out_plan4_a', 'opt_plan4_a', 'Todo el equipo pudo consultar el plan cuando hizo falta.', 15),
  ('out_plan4_b', 'opt_plan4_b', 'Casi todos recordaron el plan, con alguna pequena diferencia.', 8),
  ('out_plan4_c', 'opt_plan4_c', 'Cada uno recordo el plan de una forma distinta.', 2),
  ('out_plan5_a', 'opt_plan5_a', 'Cuando surgio un imprevisto, el equipo tuvo tiempo para resolverlo.', 15),
  ('out_plan5_b', 'opt_plan5_b', 'El imprevisto se resolvio, pero atraso el resto del plan.', 8),
  ('out_plan5_c', 'opt_plan5_c', 'El imprevisto dejo al equipo sin tiempo para terminar.', 2);

INSERT INTO project (projectId, title, description, minAgeBand) VALUES
  ('proj_feria_ideas', 'Feria de Ideas', 'Organiza una feria donde cada equipo presenta un pequeno invento.', '10-12'),
  ('proj_mural_aula', 'Gran Mural del Aula', 'Disena y construye un mural colaborativo para decorar el aula.', '8-9'),
  ('proj_obra_teatro', 'Pequena Obra de Teatro', 'Prepara una funcion breve entre varios equipos.', '10-12'),
  ('proj_jardin_clase', 'Jardin de la Clase', 'Organiza un pequeno rincon de plantas cuidado entre todos.', '8-9'),
  ('proj_periodico_mural', 'Periodico Mural', 'Crea un periodico con noticias del aula para todo el curso.', '10-12'),
  ('proj_museo_clase', 'Museo de la Clase', 'Monta una pequena exposicion con objetos y descubrimientos del curso.', '10-12');

INSERT INTO project_task (taskId, projectId, orderIndex, taskType, label) VALUES
  ('proj_feria_ideas_t1', 'proj_feria_ideas', 0, 'DECIDIR', 'Decidir que actividad se va a realizar'),
  ('proj_feria_ideas_t2', 'proj_feria_ideas', 1, 'MATERIALES', 'Organizar los materiales necesarios'),
  ('proj_feria_ideas_t3', 'proj_feria_ideas', 2, 'EQUIPO', 'Distribuir tareas entre el equipo'),
  ('proj_feria_ideas_t4', 'proj_feria_ideas', 3, 'ESPACIO', 'Preparar el espacio de trabajo'),
  ('proj_feria_ideas_t5', 'proj_feria_ideas', 4, 'TIEMPO', 'Planificar el tiempo disponible'),
  ('proj_feria_ideas_t6', 'proj_feria_ideas', 5, 'IMPREVISTO', 'Resolver un imprevisto de ultima hora'),
  ('proj_feria_ideas_t7', 'proj_feria_ideas', 6, 'PRESENTAR', 'Presentar el resultado final'),
  ('proj_mural_aula_t1', 'proj_mural_aula', 0, 'DECIDIR', 'Decidir que actividad se va a realizar'),
  ('proj_mural_aula_t2', 'proj_mural_aula', 1, 'MATERIALES', 'Organizar los materiales necesarios'),
  ('proj_mural_aula_t3', 'proj_mural_aula', 2, 'EQUIPO', 'Distribuir tareas entre el equipo'),
  ('proj_mural_aula_t4', 'proj_mural_aula', 3, 'ESPACIO', 'Preparar el espacio de trabajo'),
  ('proj_mural_aula_t5', 'proj_mural_aula', 4, 'TIEMPO', 'Planificar el tiempo disponible'),
  ('proj_mural_aula_t6', 'proj_mural_aula', 5, 'IMPREVISTO', 'Resolver un imprevisto de ultima hora'),
  ('proj_mural_aula_t7', 'proj_mural_aula', 6, 'PRESENTAR', 'Presentar el resultado final'),
  ('proj_obra_teatro_t1', 'proj_obra_teatro', 0, 'DECIDIR', 'Decidir que actividad se va a realizar'),
  ('proj_obra_teatro_t2', 'proj_obra_teatro', 1, 'MATERIALES', 'Organizar los materiales necesarios'),
  ('proj_obra_teatro_t3', 'proj_obra_teatro', 2, 'EQUIPO', 'Distribuir tareas entre el equipo'),
  ('proj_obra_teatro_t4', 'proj_obra_teatro', 3, 'ESPACIO', 'Preparar el espacio de trabajo'),
  ('proj_obra_teatro_t5', 'proj_obra_teatro', 4, 'TIEMPO', 'Planificar el tiempo disponible'),
  ('proj_obra_teatro_t6', 'proj_obra_teatro', 5, 'IMPREVISTO', 'Resolver un imprevisto de ultima hora'),
  ('proj_obra_teatro_t7', 'proj_obra_teatro', 6, 'PRESENTAR', 'Presentar el resultado final'),
  ('proj_jardin_clase_t1', 'proj_jardin_clase', 0, 'DECIDIR', 'Decidir que actividad se va a realizar'),
  ('proj_jardin_clase_t2', 'proj_jardin_clase', 1, 'MATERIALES', 'Organizar los materiales necesarios'),
  ('proj_jardin_clase_t3', 'proj_jardin_clase', 2, 'EQUIPO', 'Distribuir tareas entre el equipo'),
  ('proj_jardin_clase_t4', 'proj_jardin_clase', 3, 'ESPACIO', 'Preparar el espacio de trabajo'),
  ('proj_jardin_clase_t5', 'proj_jardin_clase', 4, 'TIEMPO', 'Planificar el tiempo disponible'),
  ('proj_jardin_clase_t6', 'proj_jardin_clase', 5, 'IMPREVISTO', 'Resolver un imprevisto de ultima hora'),
  ('proj_jardin_clase_t7', 'proj_jardin_clase', 6, 'PRESENTAR', 'Presentar el resultado final'),
  ('proj_periodico_mural_t1', 'proj_periodico_mural', 0, 'DECIDIR', 'Decidir que actividad se va a realizar'),
  ('proj_periodico_mural_t2', 'proj_periodico_mural', 1, 'MATERIALES', 'Organizar los materiales necesarios'),
  ('proj_periodico_mural_t3', 'proj_periodico_mural', 2, 'EQUIPO', 'Distribuir tareas entre el equipo'),
  ('proj_periodico_mural_t4', 'proj_periodico_mural', 3, 'ESPACIO', 'Preparar el espacio de trabajo'),
  ('proj_periodico_mural_t5', 'proj_periodico_mural', 4, 'TIEMPO', 'Planificar el tiempo disponible'),
  ('proj_periodico_mural_t6', 'proj_periodico_mural', 5, 'IMPREVISTO', 'Resolver un imprevisto de ultima hora'),
  ('proj_periodico_mural_t7', 'proj_periodico_mural', 6, 'PRESENTAR', 'Presentar el resultado final'),
  ('proj_museo_clase_t1', 'proj_museo_clase', 0, 'DECIDIR', 'Decidir que actividad se va a realizar'),
  ('proj_museo_clase_t2', 'proj_museo_clase', 1, 'MATERIALES', 'Organizar los materiales necesarios'),
  ('proj_museo_clase_t3', 'proj_museo_clase', 2, 'EQUIPO', 'Distribuir tareas entre el equipo'),
  ('proj_museo_clase_t4', 'proj_museo_clase', 3, 'ESPACIO', 'Preparar el espacio de trabajo'),
  ('proj_museo_clase_t5', 'proj_museo_clase', 4, 'TIEMPO', 'Planificar el tiempo disponible'),
  ('proj_museo_clase_t6', 'proj_museo_clase', 5, 'IMPREVISTO', 'Resolver un imprevisto de ultima hora'),
  ('proj_museo_clase_t7', 'proj_museo_clase', 6, 'PRESENTAR', 'Presentar el resultado final');
